export const defaultEcsServiceResourceProperties = {
  ServiceToken: 'foo',
  Cluster: 'foo',
  ServiceName: 'foo',
  ContainerName: 'foo',
  TaskDefinition: 'foo',
  LaunghType: 'foo',
  PlatformVersion: '1.1.0',
  DesiredCount: 1,
  Subnets: ['foo'],
  SecurityGroups: ['foo'],
  TargetGroupArn: 'foo',
  ContainerPort: 8080,
  SchedulingStrategy: 'foo',
  HealthCheckGracePeriodSeconds: 3,
  DeploymentConfiguration: {},
  PropogateTags: 'SERVICE',
  Tags: [],
};
