name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["14", "16"]
    name: Node ${{ matrix.node }} build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Installing
        run: yarn install --frozen-lockfile
      - name: Linting
        run: yarn lint
      - name: Testing
        run: yarn test
        env:
          NODE_OPTIONS: --max_old_space_size=4096
      #- name: Anti-tamper check
      #  run: git diff --exit-code
    container:
      image: jsii/superchain:1-buster-slim
